graph:
  database: titan
  host: localhost
  keyspace: gaua
  migrations: ["GaiaBmegMigration"]
server:
  port: 11223
  facets:
    IndividualFacet: individual
    GeneFacet: gene
    SignatureFacet: signature
