graph:
  database: janus
  host: localhost
  keyspace: prototest
  migrations: ["GaiaBmegMigration"]
  protograph: bmeg.protograph.yml
server:
  port: 11223
  facets:
    IndividualFacet: individual
    GeneFacet: gene
    SignatureFacet: signature
